src/Entity/News.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News implements EntityInterface
{

    use TimestampableEntity;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     *
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $short_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $main_photo;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMainPhoto(): ?string
    {
        return $this->main_photo;
    }

    public function setMainPhoto(?string $main_photo): self
    {
        $this->main_photo = $main_photo;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

}

src/Form/NewsType.php
<?php


namespace App\Form;


use App\Model\NewsModel;
use App\Model\NewsTypeModel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewsType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Заголовок'
            ])
            ->add('short_description', TextareaType::class, [
                'label' => 'Короткий опис'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Опис',
            ])
            ->add('articleType', ChoiceType::class, [
                'label' => 'Тип новини',
                'choices' => [
                    new NewsTypeModel(),
                    new NewsTypeModel('Актуальні'),
                    new NewsTypeModel('Про профспілку'),
                ],
                'choice_label' => function(NewsTypeModel $newsTypeModel){
                            return $newsTypeModel->getName();
                },
                'choice_value' => function(?NewsTypeModel $newsTypeModel){
                    if(!$newsTypeModel)
                        return null;
                    return $newsTypeModel->getName();
                },
                'required' => false

            ])
            ->add('isActive',CheckboxType::class,[
                'label' => "Активна",
                'required' => false
            ])
            ->add('mainPhoto',FileType::class,[
                'label' => "Фотографія",
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => NewsModel::class,
        ]);
    }
}

src/Controller/Admin/NewsController.php
<?php


namespace App\Controller\Admin;

use App\DataMapper\NewsMapper;
use App\Entity\News;
use App\Form\NewsType;
use App\Model\NewsModel;
use App\Services\NewsService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\{Request, Response};


class NewsController extends AbstractController
{
    /**
     * @var NewsService
     */
    private $newsService;

    /**
     * @var NewsMapper
     */
    private $mapper;

    public function __construct(NewsService $newsService, NewsMapper $mapper)
    {
        $this->newsService = $newsService;
        $this->mapper = $mapper;
    }

    public function index()
    {
        $news = $this->newsService->findBy([], ['createdAt' => 'DESC']);

        return $this->render('admin/news/index.html.twig', [
            'news' => $news,
        ]);
    }

    public function create(Request $request): Response
    {
        $form = $this->createForm(NewsType::class);
        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $this->newsService->create($data, new News());

            return $this->redirectToRoute('admin_news_index');
        }

        return $this->render('admin/news/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function update(News $news, Request $request): Response
    {
        $model = $this->mapper->entityToModel($news);

        $form = $this->createForm(NewsType::class, $model);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $this->newsService->update($data, $news);

            return $this->redirectToRoute('admin_news_index');
        }

        return $this->render('admin/news/update.html.twig', [
            'form' => $form->createView()
        ]);

    }

    public function delete(News $news)
    {
        $this->newsService->delete($news);

        return $this->redirectToRoute('admin_news_index');
    }
}

src/Controller/NewsController.php
<?php


namespace App\Controller;


use App\Entity\News;
use App\Services\NewsService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class NewsController extends AbstractController
{
    /**
     * @var NewsService
     */
    private $newsService;

    /**
     * NewsController constructor.
     * @param NewsService $newsService
     */
    public function __construct(NewsService $newsService)
    {
        $this->newsService = $newsService;
    }

    public function index()
    {
        /** @var News[] $news */
        $news = $this->newsService->findBy([], ['createdAt' => 'DESC']);
        return $this->render('news/news.html.twig', ['news' => $news]);
    }

    public function newsPost(News $news)
    {
        return $this->render('news/single_post.html.twig', ['post' => $news]);
    }
}

templates/news/news.html.twig
{% extends 'public.html.twig' %}
{% block title %}
    Новини
{% endblock %}
{% block stylesheets %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/main.css?v=1.0">
    <link rel="stylesheet" href="/css/news-page.css?v=1.0">
    <link rel="stylesheet" href="/css/media-queries/main_responsive.css?v=1.0">
    <link rel="stylesheet" href="/css/media-queries/news-page_responsive.css?v=1.0">
{% endblock %}
{% block body %}
    {% include 'elements/mobile_header.html.twig' %}
    <div class="single-chill_wrapper page-wrapper">
        <section class="page-hero page-hero_news">
            <div class="page-hero__container">
                {% include 'elements/header.html.twig' %}
            </div>
            <div class="header_title">
                Новини
            </div>
        </section>
        <div class="news_wrapper" id="news_wrapper">
            {% for post in news %}
                <div class="news">
                    <div class="post_content">
                        <img class="news_img" src="/uploads/{{ post.mainPhoto }}" alt="">
                        <div class="news_date">
                            <p>
                                {{ post.createdAt|date('Y-m-j') }}
                            </p>
                        </div>
                        <div class="post_title">
                            {{ post.title }}
                        </div>
                        <div class="post_text">
                            {{ post.shortDescription|raw }}
                        </div>
                        <div class="view_more">
                            <a href="{{ path('news_post', {'slug': post.slug}) }}">
                                Дивитись далі
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% include 'elements/footer.html.twig' %}
    </div>
{% endblock %}

templates/news/single_post.html.twig
{% extends 'public.html.twig' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block stylesheets %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/main.css?v=1.0">
    <link rel="stylesheet" href="/css/single-post-page.css?v=1.0">
    <link rel="stylesheet" href="/css/media-queries/main_responsive.css?v=1.0">
    <link rel="stylesheet" href="/css/media-queries/single-post-page_responsive.css?v=1.0">
{% endblock %}
{% block body %}
    {% include 'elements/mobile_header.html.twig' %}
    <div class="single-chill_wrapper page-wrapper">
        <section class="page-hero page-hero_news">
            <div class="page-hero__container">
                {% include 'elements/header.html.twig' %}
            </div>
        </section>
        <div class="post_wrapper">
            <div class="post_wrapper-content">
                <img class="post_img" src="/uploads/{{ post.mainPhoto }}" alt="">
                <div class="post">
                    <div class="post_title">
                        {{ post.title }}
                    </div>
                    <div class="post_text" style="font-family: FuturaMediumC, sans-serif;">
                        {{ post.description|raw }}
                    </div>
                    <div class="post_date">
                            {{ post.createdAt|date('Y-m-j') }}
                    </div>
                </div>
            </div>
        </div>
        {% include 'elements/footer.html.twig' %}
    </div>
{% endblock %}


{#{% block javascripts %}#}
{#    {{ parent() }}#}
{#    <script>#}
{#        $('iframe').each(function () {#}
{#            $(this).css('width', '95vw');#}
{#        })#}
{#    </script>#}
{#{% endblock %}#}